CREATE TABLE USER (
	USER_ID VARCHAR(255) PRIMARY KEY,
  	AGE INT
);

INSERT INTO USER (USER_ID, AGE) VALUES ('WILDAN', 27);
INSERT INTO USER (USER_ID, AGE) VALUES ('ZAKI', 25);

SELECT * FROM USER;

CREATE TABLE ASSET (
	ITEM VARCHAR,
  	USER_ID VARCHAR,
        FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID)
);

INSERT INTO ASSET (ITEM, USER_ID) VALUES ('NOTEBOOK', 'WILDAN');
INSERT INTO ASSET (ITEM, USER_ID) VALUES ('BAG', 'WILDAN');
INSERT INTO ASSET (ITEM, USER_ID) VALUES ('NOTEBOOK', 'ZAKI');
INSERT INTO ASSET (ITEM, USER_ID) VALUES ('BAG', 'ZAKI');
INSERT INTO ASSET (ITEM, USER_ID) VALUES ('MOBILE PHONE', 'ZAKI');

SELECT * FROM ASSET;

SELECT DISTINCT ITEM FROM ASSET;

SELECT u.USER_ID, GROUP_CONCAT(a.ITEM) AS ASSET
FROM USER u
INNER JOIN ASSET a ON u.USER_ID = a.USER_ID
GROUP BY u.USER_ID;


```

tested in sqlite3 with the result of the following

USER_ID|AGE
WILDAN|27
ZAKI|25

ITEM|USER_ID
NOTEBOOK|WILDAN
BAG|WILDAN
NOTEBOOK|ZAKI
BAG|ZAKI
MOBILE PHONE|ZAKI

-- Result 1
ITEM
NOTEBOOK
BAG
MOBILE PHONE


-- Result 2
USER_ID|ASSET
WILDAN|NOTEBOOK,BAG
ZAKI|NOTEBOOK,BAG,MOBILE PHONE


```